image:
  file: .gitpod.Dockerfile

tasks:
  - name: ServiceMailSenderPro
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project WorkerServiceApp"
    openMode: tab-after
  - name: ServiceSelectBonosProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project WorkerServiceApp2"
    openMode: tab-after
  - name: ServiceWorkerComprasFiatProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project WorkerServiceApp3"
    openMode: tab-after
  - name: ServiceWorkerDispersorPagosProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project WorkerServiceApp4"
    openMode: tab-after
  - name: ServiceWorkerMembershipNotificationsProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project WorkerServiceApp5"
    openMode: tab-after
  - name: ServiceWorkerMonitorComprasBlockChain
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project WorkerServiceApp6"
    openMode: tab-after
  - name: ServiceWorkerMonitorPagosProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project WorkerServiceApp7"
    openMode: tab-after
  - name: ServiceWorkerProcesadorRetirosProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project WorkerServiceApp8"
    openMode: tab-after
  - name: Run sqlserver
    init: docker-compose -f docker/sqlserver/docker-compose.yaml up -d
    openMode: tab-after

vscode:
  extensions:
    - ms-dotnettools.vscode-dotnet-runtime
    - mtxr.sqltools
    - mtxr.sqltools-driver-mssql
    - ms-azuretools.vscode-docker
    - muhammad-sammy.csharp
