image:
  file: .gitpod.Dockerfile

tasks:
  - name: Terminal 1
    init: echo "Iniciando Terminal 1"
    openMode: tab-after
  - name: Terminal 2
    init: echo "Iniciando Terminal 2"
    openMode: tab-after
  - name: Terminal 3
    init: echo "Iniciando Terminal 3"
    openMode: tab-after
  - name: Terminal 4
    init: echo "Iniciando Terminal 4"
    openMode: tab-after
  - name: Terminal 5
    init: echo "Iniciando Terminal 5"
    openMode: tab-after
  - name: Terminal 6
    init: echo "Iniciando Terminal 6"
    openMode: tab-after
  - name: Terminal 7
    init: echo "Iniciando Terminal 7"
    openMode: tab-after
  - name: Terminal 8
    init: echo "Iniciando Terminal 8"
    openMode: tab-after
  - name: Run sqlserver
    init: docker-compose -f docker/sqlserver/docker-compose.yaml up -d

vscode:
  extensions:
    - ms-dotnettools.vscode-dotnet-runtime
