image:
  file: .gitpod.Dockerfile

tasks:
  - name: ServiceMailSenderPro
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project ServiceMailSenderPro"
    openMode: tab-after
  - name: ServiceSelectBonosProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project ServiceSelectBonosProd"
    openMode: tab-after
  - name: ServiceWorkerComprasFiatProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project ServiceWorkerComprasFiatProd"
    openMode: tab-after
  - name: ServiceWorkerDispersorPagosProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project ServiceWorkerDispersorPagosProd"
    openMode: tab-after
  - name: ServiceWorkerMembershipNotificationsProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project ServiceWorkerMembershipNotificationsProd"
    openMode: tab-after
  - name: ServiceWorkerMonitorComprasBlockChain
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project ServiceWorkerMonitorComprasBlockChain"
    openMode: tab-after
  - name: ServiceWorkerMonitorPagosProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project ServiceWorkerMonitorPagosProd"
    openMode: tab-after
  - name: ServiceWorkerProcesadorRetirosProd
    command: |
      echo "Para iniciar el batch ejecute el siguiente comando:"
      echo "dotnet run --project ServiceWorkerProcesadorRetirosProd"
    openMode: tab-after
  - name: Run sqlserver
    init: docker-compose -f docker/sqlserver/docker-compose.yaml up -d
    openMode: tab-after

vscode:
  extensions:
    - ms-dotnettools.vscode-dotnet-runtime
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - ms-azuretools.vscode-docker
    - muhammad-sammy.csharp
