name: Build

on:
  push:
    branches: [ develop ]

jobs:
  build-deploy-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#--------------------------------------------------
# Build
#--------------------------------------------------
