services:
  sqlserver:
    user: root
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    container_name: smart-workers-sqlserver
    ports:
      - "127.0.0.1:1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_DATABASE: "${MSSQL_DATABASE}"
      MSSQL_SLEEP: "${MSSQL_SLEEP}"
    command: >
      bash -c " /opt/mssql/bin/sqlservr & \
      echo 'wait ${MSSQL_SLEEP} sec for DB to start'; \
      sleep ${MSSQL_SLEEP}; \
      /opt/mssql-tools/bin/sqlcmd -U sa -P ${SA_PASSWORD} -d tempdb -q \"IF DB_ID('${MSSQL_DATABASE}') IS NULL CREATE DATABASE [${MSSQL_DATABASE}];\"; \
      wait;"
    healthcheck:
      test: "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    privileged: true


volumes:
  mssql_data:
