services:
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    container_name: smart-workers-sqlserver
    ports:
      - "1433:1433"
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      SA_PASSWORD: "mssql1Ipw" # cambiar por una contraseña segura
      ACCEPT_EULA: "Y"


