services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: mssql1Ipw
      POSTGRES_DB: smart-database
      POSTGRES_SLEEP: 30
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
